<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pig</string>
	</array>
	<key>name</key>
	<string>Pig</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.pig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(--).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.asciidoc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(load|store|dump|filter|distinct|foreach|generate|stream|join|cogroup|group|cross|order|limit|union|split|describe|explain|illustrate|register|define|as|by|into|using|limit|parallel|outer|LOAD|STORE|DUMP|FILTER|DISTINCT|FOREACH|GENERATE|STREAM|JOIN|COGROUP|GROUP|CROSS|ORDER|LIMIT|UNION|SPLIT|DESCRIBE|EXPLAIN|ILLUSTRATE|REGISTER|DEFINE|AS|BY|INTO|USING|LIMIT|PARALLEL|OUTER)\b</string>
			<key>name</key>
			<string>keyword.pig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(int|long|float|double|chararray|bytearray)\b</string>
			<key>name</key>
			<string>storage.datatypes.pig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(FLATTEN|AVG|CONCAT|COUNT|DIFF|MAX|MIN|SIZE|SUM|TOKENIZE|IsEmpty|PigStorage|BinStorage|BinaryStorage|TextLoader|PigDump)\b</string>
			<key>name</key>
			<string>entity.function.pig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[0-9]+</string>
			<key>name</key>
			<string>variable.pig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(!=|==|&lt;|&gt;|&lt;=|&gt;=| matches| is null| is not null|or| and| not)\b</string>
			<key>name</key>
			<string>keyword.operator.comparison.pig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\+|\-|\*|\/|\%)\b</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.pig</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.pig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.pig</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.pig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.pig</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pig</string>
	<key>uuid</key>
	<string>6B102D86-1EB7-4729-94E5-8EE7D3D6F82B</string>
</dict>
</plist>
